"use client";

import { FormEvent, useMemo, useState } from "react";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";
import { MahesaChart } from "@/components/mahesa-gantari/MahesaChart";
import { HealthCard } from "@/components/mahesa-gantari/HealthCard";
import { calculateMahesaGantari, type CourseLine, type CoursePoint, type MahesaGantariResult, type Sect } from "@/lib/mahesa-gantari";
import type { LanguageCode } from "@/lib/types";

const COPY = {
  en:{title:"Mahesa Gantari Calculation Lab", experimental:"Experimental", unverified:"Not teacher-verified", intro:"A complete, course-transcribed calculation workspace designed for transparent inspection. No predictions or interpretations are generated.", birth:"Birth date", sect:"Sect context", day:"Day", night:"Night", unknown:"Unknown", calculate:"Calculate", clear:"Clear", context:"Day/night is recorded as context only and does not change calculations or interpretations.", empty:"Enter a birth date to inspect every calculated point, line, and purpose value.", loading:"Calculating…", inspector:"Selected point", trace:"Calculation trace", evidence:"Evidence", source:"Source page", lines:"Domain lines", purpose:"Purpose calculations", warnings:"Methodology warnings", age:"Age-range metadata", select:"Select", inactive:"Sect weighting inactive", status:"course_transcribed"},
  id:{title:"Lab Perhitungan Mahesa Gantari", experimental:"Eksperimental", unverified:"Belum diverifikasi guru", intro:"Ruang kerja perhitungan lengkap hasil transkripsi materi kursus, dirancang untuk inspeksi transparan. Tidak ada prediksi atau interpretasi yang dibuat.", birth:"Tanggal lahir", sect:"Konteks sekte", day:"Siang", night:"Malam", unknown:"Tidak diketahui", calculate:"Hitung", clear:"Bersihkan", context:"Siang/malam hanya dicatat sebagai konteks dan tidak mengubah perhitungan atau interpretasi.", empty:"Masukkan tanggal lahir untuk memeriksa setiap titik, garis, dan nilai tujuan yang dihitung.", loading:"Menghitung…", inspector:"Titik terpilih", trace:"Jejak perhitungan", evidence:"Bukti", source:"Halaman sumber", lines:"Garis domain", purpose:"Perhitungan tujuan", warnings:"Peringatan metodologi", age:"Metadata rentang usia", select:"Pilih", inactive:"Pembobotan sekte tidak aktif", status:"course_transcribed"}
};

const LINE_NAMES: Record<string,Record<LanguageCode,string>> = {
  money_line:{en:"Money Line",id:"Garis Uang"}, relationship_line:{en:"Relationship Line",id:"Garis Relasi"}, karmic_tail:{en:"Karmic Tail",id:"Ekor Karma"}, deepest_desire:{en:"Deepest Desire",id:"Hasrat Terdalam"}, male_generation:{en:"Male Generation Line",id:"Garis Generasi Pria"}, female_generation:{en:"Female Generation Line",id:"Garis Generasi Wanita"}
};

const POINT_LABELS_ID: Record<string,string> = { E_plus_J:"E tambah J" };

function Evidence({point,language}:{point:CoursePoint;language:LanguageCode}) { const c=COPY[language]; return <>
  <div><span className="text-xs font-bold uppercase text-night/50">{c.trace}</span><ol className="mt-2 space-y-2 border-l-2 border-gold pl-4 font-mono text-xs sm:text-sm">{point.calculation_trace.map((x,i)=><li key={`${i}-${x}`} className="break-words">{x}</li>)}</ol></div>
  <div className="grid gap-3 text-sm sm:grid-cols-2"><p><span className="block text-xs font-bold uppercase text-night/50">{c.evidence}</span>{point.evidence.evidence_status.replaceAll("_"," ")}</p><p><span className="block text-xs font-bold uppercase text-night/50">{c.source}</span>{point.evidence.source_page}</p></div>
  <p className="font-mono text-sm font-bold text-red-800">verified: false</p>
  </>; }

export default function MahesaGantariLab() {
  const [language,setLanguage]=useState<LanguageCode>("en"); const [birthDate,setBirthDate]=useState(""); const [sect,setSect]=useState<Sect>("unknown");
  const [result,setResult]=useState<MahesaGantariResult|null>(null); const [selected,setSelected]=useState("E"); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
  const c=COPY[language];
  const pointMap=useMemo(()=>new Map(result?.points.map(p=>[p.position_id,p])??[]),[result]);
  const selectedPoint=pointMap.get(selected);
  const lines:CourseLine[] = result ? [result.money_line,result.relationship_line,result.karmic_tail,result.deepest_desire,result.male_generation,result.female_generation] : [];
  const purposes = result ? [result.purpose.earth,result.purpose.sky,result.purpose.soul_searching,result.purpose.male,result.purpose.female,result.purpose.socialization,result.purpose.spiritual_knowledge] : [];
  async function submit(e:FormEvent){e.preventDefault(); if(!birthDate){setError(c.empty);return;} setLoading(true);setError(null);try{const data=await calculateMahesaGantari(birthDate,sect);setResult(data);setSelected("E");}catch(x){setError(x instanceof Error?x.message:"Request failed");}finally{setLoading(false)}}
  function clear(){setBirthDate("");setSect("unknown");setResult(null);setError(null);setSelected("E")}
  return <main className="min-h-screen bg-[#12101d] px-4 py-6 text-cream sm:px-6 lg:px-8"><div className="mx-auto max-w-[1500px]">
    <header className="border-b border-gold/30 pb-6"><div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-4xl"><div className="flex flex-wrap gap-2"><span className="border border-gold/60 bg-gold/10 px-3 py-2 text-xs font-bold uppercase text-gold">{c.experimental}</span><span className="border border-red-300/40 bg-red-950/30 px-3 py-2 text-xs font-bold uppercase text-red-200">{c.unverified}</span></div><h1 className="mt-4 text-3xl font-bold sm:text-4xl">{c.title}</h1><p className="mt-3 max-w-3xl leading-7 text-mist/80">{c.intro}</p></div><div className="space-y-2 border border-cream/15 bg-night/80 p-4 text-sm"><p className="font-mono text-gold">mahesa-gantari-rws-v0.1</p><p>{c.status}</p><p className="font-mono font-bold text-red-200">verified: false</p><p className="font-semibold text-emerald-300">{c.inactive}</p></div></div></header>
    <section className="mt-6 grid gap-5 border border-cream/15 bg-night/65 p-4 lg:grid-cols-[1fr_auto]"><form onSubmit={submit} className="grid items-end gap-4 sm:grid-cols-[minmax(180px,1fr)_minmax(180px,1fr)_auto]"><label className="text-sm font-bold">{c.birth}<input type="date" value={birthDate} onChange={e=>setBirthDate(e.target.value)} required className="mt-2 min-h-12 w-full border border-cream/20 bg-white px-3 text-night focus:outline-none focus:ring-2 focus:ring-gold"/></label><label className="text-sm font-bold">{c.sect}<select value={sect} onChange={e=>setSect(e.target.value as Sect)} className="mt-2 min-h-12 w-full border border-cream/20 bg-white px-3 text-night focus:outline-none focus:ring-2 focus:ring-gold"><option value="unknown">{c.unknown}</option><option value="day">{c.day}</option><option value="night">{c.night}</option></select></label><div className="flex gap-2"><button disabled={loading} className="min-h-12 bg-gold px-5 font-bold text-night focus:outline-none focus:ring-2 focus:ring-white disabled:opacity-60">{loading?c.loading:c.calculate}</button><button type="button" onClick={clear} className="min-h-12 border border-cream/30 px-4 font-bold focus:outline-none focus:ring-2 focus:ring-gold">{c.clear}</button></div></form><LanguageSwitcher value={language} onChange={setLanguage}/><p className="text-sm text-gold lg:col-span-2">{c.context}</p>{error&&<p role="alert" className="border border-red-400/40 bg-red-950/40 p-3 text-red-100 lg:col-span-2">{error}</p>}</section>
    {!result&&!loading?<div className="mt-8 border border-dashed border-gold/35 p-12 text-center text-cream/65">{c.empty}</div>:null}
    {result?<><section className="mt-8 grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,.8fr)]"><MahesaChart points={result.points} selected={selected} onSelect={setSelected} language={language}/>{selectedPoint&&<aside className="min-w-0 self-start bg-cream p-5 text-night xl:sticky xl:top-4"><p className="text-xs font-bold uppercase text-plum">{c.inspector}</p><h2 className="mt-2 text-2xl font-bold">{selectedPoint.position_id} · {language==="id"?(POINT_LABELS_ID[selectedPoint.position_id]??selectedPoint.label):selectedPoint.label}</h2><p className="mt-2 text-lg"><strong>{selectedPoint.value}</strong> · {selectedPoint.arcana_name}</p><div className="mt-5 space-y-5"><Evidence point={selectedPoint} language={language}/></div></aside>}</section>
    <section className="mt-8"><h2 className="text-2xl font-bold">{c.lines}</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{lines.map(line=><article key={line.line_id} className="border border-cream/15 bg-night/65 p-4"><h3 className="font-bold text-gold">{LINE_NAMES[line.line_id][language]}</h3><div className="mt-4 flex flex-wrap items-start gap-2">{line.ordered_point_ids.map((id,i)=><span key={id} className="contents"><button onClick={()=>setSelected(id)} className="min-w-0 border border-cream/20 p-2 text-left focus:outline-none focus:ring-2 focus:ring-gold"><span className="block font-mono font-bold">{id} · {line.values[i]}</span><span className="block max-w-40 text-xs text-cream/60">{line.component_labels[i]}</span></button>{i<line.values.length-1&&<span aria-hidden className="pt-3 text-gold">→</span>}</span>)}</div><p className="mt-3 text-xs text-cream/55">{c.source}: {line.evidence.source_page} · {line.evidence.evidence_status.replaceAll("_"," ")}</p></article>)}</div></section>
    <section className="mt-8"><h2 className="text-2xl font-bold">{c.purpose}</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{purposes.map(point=><details key={point.position_id} className="border border-cream/15 bg-night/65 p-4"><summary className="cursor-pointer font-bold text-gold focus:outline-none focus:ring-2 focus:ring-gold">{point.label}: {point.value} · {point.arcana_name}</summary><div className="mt-4 space-y-4 bg-cream p-4 text-night"><Evidence point={point} language={language}/>{result.purpose.age_range_metadata[point.position_id]&&<p><strong>{c.age}:</strong> {result.purpose.age_range_metadata[point.position_id]}</p>}</div></details>)}</div></section>
    <HealthCard data={result.health_card} language={language}/>
    <section className="my-8 border border-amber-300/25 bg-amber-950/20 p-4"><h2 className="font-bold text-amber-200">{c.warnings}</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-cream/75">{result.warnings.map(w=><li key={w}>{w}</li>)}</ul><p className="mt-3 text-sm text-gold">{c.sect}: {result.sect_context.sect} · {c.inactive}</p></section></>:null}
  </div></main>;
}
